In [9]:
# 池化层是为了缓解卷积层对位置的过度敏感性
# 二维最大池化层和平均池化层
# pool2d的实现
import torch
from torch import nn
def pool2d(X,pool_size,mode='max'):
    X = X.float()
    p_h,p_w = pool_size
    Y = torch.zeros(X.shape[0] - p_h + 1,X.shape[1] - p_w + 1)
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            if mode == 'max':
                Y[i,j] = X[i:i+p_h,j:j+p_w].max()
            elif mode == 'avg':
                Y[i,j] = X[i:i+p_h,j:j+p_w].mean()
    return Y
X = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
pool2d(X, (2, 2))

tensor([[4., 5.],
        [7., 8.]])

In [12]:
pool2d(X, (2, 2),'avg')

tensor([[2., 3.],
        [5., 6.]])

In [13]:
# 填充和步长
X = torch.arange(16,dtype = torch.float).view((1,1,4,4))
X

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [14]:
pool2d = nn.MaxPool2d(3)# 默认步长和池化层的尺寸相同
pool2d(X)

tensor([[[[10.]]]])

In [16]:
# 也可以设置步长和填充（strides and padding）
pool2d = nn.MaxPool2d(3,padding=1,stride=2)
pool2d(X)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [17]:
pool2d = nn.MaxPool2d((2,4),padding=(1,2),stride=(2,3))
pool2d(X)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

In [ ]:
# 多通道
